"""create core postgres schema

Revision ID: 4d3bebc7115c
Revises: 
Create Date: 2026-07-25 20:19:38.035347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d3bebc7115c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('grade_level', sa.String(length=20), nullable=True),
    sa.Column('prerequisite_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['courses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_courses_code')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index('ix_courses_grade_level', ['grade_level'], unique=False)

    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_teachers_code'),
    sa.UniqueConstraint('email', name='uq_teachers_email')
    )
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_index('ix_teachers_status', ['status'], unique=False)
        batch_op.create_index('ix_teachers_subject', ['subject'], unique=False)

    op.create_table('school_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('grade_level', sa.String(length=20), nullable=True),
    sa.Column('homeroom_teacher_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['homeroom_teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_school_classes_code')
    )
    with op.batch_alter_table('school_classes', schema=None) as batch_op:
        batch_op.create_index('ix_school_classes_grade_level', ['grade_level'], unique=False)

    op.create_table('course_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('course_sections', schema=None) as batch_op:
        batch_op.create_index('ix_course_sections_class', ['class_id'], unique=False)
        batch_op.create_index('ix_course_sections_course', ['course_id'], unique=False)
        batch_op.create_index('ix_course_sections_teacher', ['teacher_id'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('average_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('household', sa.String(length=255), nullable=True),
    sa.Column('parent_name', sa.String(length=160), nullable=True),
    sa.Column('parent_phone', sa.String(length=40), nullable=True),
    sa.Column('learning_status', sa.String(length=40), nullable=False),
    sa.Column('policy_type', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_students_code')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index('ix_students_class_id', ['class_id'], unique=False)
        batch_op.create_index('ix_students_learning_status', ['learning_status'], unique=False)

    op.create_table('teacher_class_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'class_id', 'term', name='uq_teacher_class_assignments_scope')
    )
    with op.batch_alter_table('teacher_class_assignments', schema=None) as batch_op:
        batch_op.create_index('ix_teacher_class_assignments_class', ['class_id'], unique=False)
        batch_op.create_index('ix_teacher_class_assignments_teacher', ['teacher_id'], unique=False)

    op.create_table('admission_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_code', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('parent_name', sa.String(length=160), nullable=True),
    sa.Column('parent_phone', sa.String(length=40), nullable=True),
    sa.Column('admission_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('desired_class_id', sa.Integer(), nullable=True),
    sa.Column('desired_major', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['desired_class_id'], ['school_classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_code', name='uq_admission_applications_code')
    )
    with op.batch_alter_table('admission_applications', schema=None) as batch_op:
        batch_op.create_index('ix_admission_applications_desired_class', ['desired_class_id'], unique=False)
        batch_op.create_index('ix_admission_applications_status', ['status'], unique=False)

    op.create_table('grade_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('component_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('midterm_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('final_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('average10', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('gpa4', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('letter_grade', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['course_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'student_id', name='uq_grade_records_scope')
    )
    with op.batch_alter_table('grade_records', schema=None) as batch_op:
        batch_op.create_index('ix_grade_records_section', ['section_id'], unique=False)
        batch_op.create_index('ix_grade_records_student', ['student_id'], unique=False)

    op.create_table('graduation_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('required_credits', sa.Integer(), nullable=False),
    sa.Column('earned_credits', sa.Integer(), nullable=False),
    sa.Column('informatics_cert', sa.Boolean(), nullable=False),
    sa.Column('language_cert', sa.Boolean(), nullable=False),
    sa.Column('defense_cert', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graduation_checks', schema=None) as batch_op:
        batch_op.create_index('ix_graduation_checks_status', ['status'], unique=False)
        batch_op.create_index('ix_graduation_checks_student', ['student_id'], unique=False)

    op.create_table('tuition_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_code', sa.String(length=30), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=40), nullable=False),
    sa.Column('invoice_type', sa.String(length=40), nullable=False),
    sa.Column('credit_count', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fixed_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_code'),
    sa.UniqueConstraint('student_id', 'term', 'invoice_type', name='uq_tuition_invoice_scope')
    )
    with op.batch_alter_table('tuition_invoices', schema=None) as batch_op:
        batch_op.create_index('ix_tuition_invoices_status', ['status'], unique=False)
        batch_op.create_index('ix_tuition_invoices_student', ['student_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('student_code', sa.String(length=30), nullable=True),
    sa.Column('teacher_code', sa.String(length=30), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id'),
    sa.UniqueConstraint('teacher_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_student_code'), ['student_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_teacher_code'), ['teacher_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('module', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=True),
    sa.Column('target_id', sa.String(length=80), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=80), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_actor_id'), ['actor_id'], unique=False)

    op.create_table('diploma_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('graduation_check_id', sa.Integer(), nullable=True),
    sa.Column('registry_no', sa.String(length=80), nullable=False),
    sa.Column('diploma_no', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['graduation_check_id'], ['graduation_checks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diploma_no', name='uq_diploma_records_diploma_no'),
    sa.UniqueConstraint('registry_no', name='uq_diploma_records_registry_no')
    )
    op.create_table('grade_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_record_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('adjusted_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grade_record_id'], ['grade_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grade_reviews', schema=None) as batch_op:
        batch_op.create_index('ix_grade_reviews_status', ['status'], unique=False)

    op.create_table('payment_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_code', sa.String(length=30), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=60), nullable=False),
    sa.Column('transaction_ref', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['tuition_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_code'),
    sa.UniqueConstraint('transaction_ref', name='uq_payment_records_transaction_ref')
    )
    with op.batch_alter_table('payment_records', schema=None) as batch_op:
        batch_op.create_index('ix_payment_records_invoice', ['invoice_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_records', schema=None) as batch_op:
        batch_op.drop_index('ix_payment_records_invoice')

    op.drop_table('payment_records')
    with op.batch_alter_table('grade_reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_grade_reviews_status')

    op.drop_table('grade_reviews')
    op.drop_table('diploma_records')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_actor_id'))

    op.drop_table('activity_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_teacher_code'))
        batch_op.drop_index(batch_op.f('ix_users_student_code'))
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tuition_invoices', schema=None) as batch_op:
        batch_op.drop_index('ix_tuition_invoices_student')
        batch_op.drop_index('ix_tuition_invoices_status')

    op.drop_table('tuition_invoices')
    with op.batch_alter_table('graduation_checks', schema=None) as batch_op:
        batch_op.drop_index('ix_graduation_checks_student')
        batch_op.drop_index('ix_graduation_checks_status')

    op.drop_table('graduation_checks')
    with op.batch_alter_table('grade_records', schema=None) as batch_op:
        batch_op.drop_index('ix_grade_records_student')
        batch_op.drop_index('ix_grade_records_section')

    op.drop_table('grade_records')
    with op.batch_alter_table('admission_applications', schema=None) as batch_op:
        batch_op.drop_index('ix_admission_applications_status')
        batch_op.drop_index('ix_admission_applications_desired_class')

    op.drop_table('admission_applications')
    with op.batch_alter_table('teacher_class_assignments', schema=None) as batch_op:
        batch_op.drop_index('ix_teacher_class_assignments_teacher')
        batch_op.drop_index('ix_teacher_class_assignments_class')

    op.drop_table('teacher_class_assignments')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index('ix_students_learning_status')
        batch_op.drop_index('ix_students_class_id')

    op.drop_table('students')
    with op.batch_alter_table('course_sections', schema=None) as batch_op:
        batch_op.drop_index('ix_course_sections_teacher')
        batch_op.drop_index('ix_course_sections_course')
        batch_op.drop_index('ix_course_sections_class')

    op.drop_table('course_sections')
    with op.batch_alter_table('school_classes', schema=None) as batch_op:
        batch_op.drop_index('ix_school_classes_grade_level')

    op.drop_table('school_classes')
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_index('ix_teachers_subject')
        batch_op.drop_index('ix_teachers_status')

    op.drop_table('teachers')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index('ix_courses_grade_level')

    op.drop_table('courses')
    # ### end Alembic commands ###
