"""add phase 6 business constraints

Revision ID: dde19db034b4
Revises: 4d3bebc7115c
Create Date: 2026-07-26 01:03:54.823838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde19db034b4'
down_revision = '4d3bebc7115c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.String(length=20), nullable=False),
    sa.Column('start_period', sa.Integer(), nullable=False),
    sa.Column('end_period', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['course_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class_schedules', schema=None) as batch_op:
        batch_op.create_index('ix_class_schedules_room_slot', ['weekday', 'start_period', 'end_period', 'room'], unique=False)
        batch_op.create_index('ix_class_schedules_section', ['section_id'], unique=False)

    op.create_table('course_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['course_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'student_id', name='uq_course_registrations_scope')
    )
    with op.batch_alter_table('course_registrations', schema=None) as batch_op:
        batch_op.create_index('ix_course_registrations_section', ['section_id'], unique=False)
        batch_op.create_index('ix_course_registrations_status', ['status'], unique=False)
        batch_op.create_index('ix_course_registrations_student', ['student_id'], unique=False)

    with op.batch_alter_table('payment_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_date', sa.Date(), nullable=True))

    with op.batch_alter_table('school_classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=True))

    with op.batch_alter_table('tuition_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tuition_invoices', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    with op.batch_alter_table('school_classes', schema=None) as batch_op:
        batch_op.drop_column('capacity')

    with op.batch_alter_table('payment_records', schema=None) as batch_op:
        batch_op.drop_column('payment_date')

    with op.batch_alter_table('course_registrations', schema=None) as batch_op:
        batch_op.drop_index('ix_course_registrations_student')
        batch_op.drop_index('ix_course_registrations_status')
        batch_op.drop_index('ix_course_registrations_section')

    op.drop_table('course_registrations')
    with op.batch_alter_table('class_schedules', schema=None) as batch_op:
        batch_op.drop_index('ix_class_schedules_section')
        batch_op.drop_index('ix_class_schedules_room_slot')

    op.drop_table('class_schedules')
    # ### end Alembic commands ###
